env:
  contexts:
  - name: baseline
    urls:
    - http://webapp-frontend:4200
    excludePaths: []
    authentication:
      method: json
      parameters:
        loginPageUrl: http://webapp-frontend:4200/api/auth/login
        loginRequestData: '{"username":"{%username%}","password":"{%password%}"}'
      verification:
        method: response
        loggedInRegex: '"token":'
        loggedOutRegex: '"message"'
    sessionManagement:
      method: headers
      parameters:
        headers: "Authorization: Bearer {%json:token%}"
    users:
    - name: admin
      credentials:
        username: admin
        password: password
    - name: user
      credentials:
        username: user
        password: password
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    context: baseline
    user: admin
    maxDuration: 2
    url: http://webapp-frontend:4200
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    context: baseline
    user: admin
    maxDuration: 0
    recurse: true
  type: activeScan
- parameters:
    format: Long
    summaryFile: /zap/wrk/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: full.html
    reportTitle: ZAP Full Scan Report
    template: traditional-html
  type: report
