env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://spa_security_test-webapp-frontend:4200/home
    - http://spa_security_test-webapp-frontend:4200/
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://spa_security_test-webapp-frontend:4200/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
